# Generated by Django 4.0.4 on 2022-05-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_image', models.ImageField(upload_to='author')),
                ('author_comment', models.TextField()),
                ('tag', models.ManyToManyField(to='articles.tag')),
            ],
        ),
    ]
